[package]
name = "devefi-icp-ledger"
version = "1.4.3"
description = "Local ICP ledger syncing with remote ledger"
repository = "https://github.com/Neutrinomic/devefi_icp_ledger"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
map = "9.0.1"
swb = "1.1.1"
stableheapbtreemap = "1.5.0"
itertools = "0.2.1"
base = "0.12.1"
